### ISSUE TITLE
Causes a stop/start cycle of NodeRed

### ISSUE THREAD

**Issue by beccsjb** [ItsEcholot/node-red-contrib-snmp-trap-listener#6]
Hi, As soon as this was installed on our nodered v0.20.8 instance it caused a loop of restarts of the nodered service. After disabled the flow the node was placed on, it recovered. 
Installed node via palette on another nodered instance (same version) and experienced the same issues. Unable to use this node due to crashing on NodeRed V0.20.8

**Comment by ItsEcholot** [comment]
Can you provide some logs or a stacktrace of the crash?

**Comment by beccsjb** [comment]
Log During Install;

-----------------------------------------------------------
2019-10-22T06:08:46.526Z Install : node-red-contrib-snmp-trap-listener 1.3.0

2019-10-22T06:08:46.470Z npm install --no-audit --no-update-notifier --save --save-prefix="~" --production node-red-contrib-snmp-trap-listener@1.3.0
2019-10-22T06:09:05.259Z [err] npm
2019-10-22T06:09:05.260Z [err]  WARN deprecated nomnom@0.4.3: Package no longer supported. Contact support@npmjs.com for more info.
2019-10-22T06:09:16.207Z [out] 
2019-10-22T06:09:16.207Z [out] > dtrace-provider@0.2.8 install /home/pi/.node-red/node_modules/bunyan/node_modules/dtrace-provider
2019-10-22T06:09:16.207Z [out] > node-gyp rebuild
2019-10-22T06:09:16.207Z [out] 
2019-10-22T06:09:20.267Z [out] make: Entering directory '/home/pi/.node-red/node_modules/bunyan/node_modules/dtrace-provider/build'
2019-10-22T06:09:20.273Z [out]   TOUCH Release/obj.target/DTraceProviderStub.stamp
2019-10-22T06:09:20.290Z [out] make: Leaving directory '/home/pi/.node-red/node_modules/bunyan/node_modules/dtrace-provider/build'
2019-10-22T06:09:20.318Z [out] 
2019-10-22T06:09:20.318Z [out] > dtrace-provider@0.4.0 install /home/pi/.node-red/node_modules/dtrace-provider
2019-10-22T06:09:20.318Z [out] > node scripts/install.js
2019-10-22T06:09:20.318Z [out] 
2019-10-22T06:09:22.349Z [out] 
2019-10-22T06:09:22.349Z [out] > snmpjs@0.1.8 install /home/pi/.node-red/node_modules/snmpjs
2019-10-22T06:09:22.349Z [out] > jison -o lib/parser.js lib/snmp.jison
2019-10-22T06:09:22.349Z [out] 
2019-10-22T06:09:25.893Z [out] + node-red-contrib-snmp-trap-listener@1.3.0
2019-10-22T06:09:25.893Z [out] added 12 packages from 22 contributors in 35.185s
2019-10-22T06:09:25.930Z rc=0




Log of Crashing NodeRed Instance;
Starting as a systemd service.
22 Oct 17:10:41 - [info]
Welcome to Node-RED
===================
22 Oct 17:10:41 - [info] Node-RED version: v1.0.0
22 Oct 17:10:41 - [info] Node.js  version: v10.15.2
22 Oct 17:10:41 - [info] Linux 4.19.66-v7l+ arm LE
22 Oct 17:10:44 - [info] Loading palette nodes
22 Oct 17:10:48 - [info] Dashboard version 2.16.2 started at /ui
22 Oct 17:10:49 - [info] Settings file  : /home/pi/.node-red/settings.js
22 Oct 17:10:49 - [info] Context store  : 'default' [module=memory]
22 Oct 17:10:49 - [info] User directory : /home/pi/.node-red
22 Oct 17:10:49 - [warn] Projects disabled : editorTheme.projects.enabled=false
22 Oct 17:10:49 - [info] Flows file     : /home/pi/.node-red/flows_raspberrypi.json
22 Oct 17:10:49 - [info] Server now running at http://127.0.0.1:1880/
22 Oct 17:10:49 - [warn]
---------------------------------------------------------------------
Your flow credentials file is encrypted using a system-generated key.
If the system-generated key is lost for any reason, your credentials
file will not be recoverable, you will have to delete it and re-enter
your credentials.
You should set your own key using the 'credentialSecret' option in
your settings file. Node-RED will then re-encrypt your credentials
file using your chosen key the next time you deploy a change.
---------------------------------------------------------------------
22 Oct 17:10:49 - [info] Starting flows
22 Oct 17:10:52 - [info] [tcp in:Inception TCP OUT] connecting to 10.0.1.3:4009
22 Oct 17:10:52 - [info] [tcp out:Inception TCP IN] connecting to 10.0.1.3:4009
22 Oct 17:10:52 - [info] Started flows
22 Oct 17:10:52 - [red] Uncaught Exception:
22 Oct 17:10:52 - Error: bind EACCES 0.0.0.0:162
    at state.handle.lookup (dgram.js:242:18)
    at process._tickCallback (internal/process/next_tick.js:63:19)
nodered.service: Main process exited, code=exited, status=1/FAILURE
nodered.service: Failed with result 'exit-code'.
nodered.service: Service RestartSec=100ms expired, scheduling restart.
nodered.service: Scheduled restart job, restart counter is at 1.
Stopped Node-RED graphical event wiring tool.
Started Node-RED graphical event wiring tool.
22 Oct 17:10:56 - [info]
Welcome to Node-RED
===================
22 Oct 17:10:56 - [info] Node-RED version: v1.0.0
22 Oct 17:10:56 - [info] Node.js  version: v10.15.2
22 Oct 17:10:56 - [info] Linux 4.19.66-v7l+ arm LE
22 Oct 17:10:59 - [info] Loading palette nodes

**Comment by beccsjb** [comment]
Note that it caused the same crash on both V1.0 and v.0.20.8

**Comment by ItsEcholot** [comment]
This happens because Node-RED doesn't have the authorization to bind to the port. Run Node-RED as admin or take a look at #4 for a workaround.

```
Error: bind EACCES 0.0.0.0:162
at state.handle.lookup (dgram.js:242:18)
at process._tickCallback (internal/process/next_tick.js:63:19)
nodered.service: Main process exited, code=exited, status=1/FAILURE
nodered.service: Failed with result 'exit-code'.
nodered.service: Service RestartSec=100ms expired, scheduling restart.
nodered.service: Scheduled restart job, restart counter is at 1.
```

**Comment by beccsjb** [comment]
Ok, Thanks. Looks too complex for me. Thanks anyway though!

**Comment by ItsEcholot** [comment]
Alternative would be to choose a different port that is bigger than 1024 to listen to

**Comment by beccsjb** [comment]
I am unable to change the port on the remote SNMP devices, so i dont think that is an option unfortunately.

**Comment by ItsEcholot** [comment]
In that case the only possible solution is run Node RED als administrator or use a reverse proxy of some kind (like nginx) to proxy packets from 162 to something higher than 1024.

**Comment by Ekristoffe** [comment]
hello I know it's closed but,
have you try to do a port forwarding ? under linux it is quite simple with the default firewall.
